### ISSUE TITLE
Carga de dimensiones

### ISSUE THREAD

**Issue by azubizarretap** [azubizarretap/city_od_analyzer#21]
Gestionar la carga de dimensiones.

- [x] Carga y formateo de datos sobre ficheros basados en XML #22
- [x] Carga y formateo de datos sobre ficheros basados en JSON #23
- [x] Carga y formateo de datos sobre ficheros basados en CSV #24
- [x] Verificar tareas de carga
